// Code generated by protoc-gen-go.
// source: client.proto
// DO NOT EDIT!

/*
Package client is a generated protocol buffer package.

It is generated from these files:
	client.proto

It has these top-level messages:
	Node
	SyncOffset
	KeyExpire
	PartitionState
	CmdRequest
	CmdResponse
	BinlogSkip
	SyncRequest
*/
package client

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Type int32

const (
	Type_SYNC         Type = 0
	Type_SET          Type = 1
	Type_GET          Type = 2
	Type_DEL          Type = 3
	Type_INFOSTATS    Type = 4
	Type_INFOCAPACITY Type = 5
	Type_INFOREPL     Type = 6
	Type_MGET         Type = 7
	Type_INFOSERVER   Type = 8
)

var Type_name = map[int32]string{
	0: "SYNC",
	1: "SET",
	2: "GET",
	3: "DEL",
	4: "INFOSTATS",
	5: "INFOCAPACITY",
	6: "INFOREPL",
	7: "MGET",
	8: "INFOSERVER",
}
var Type_value = map[string]int32{
	"SYNC":         0,
	"SET":          1,
	"GET":          2,
	"DEL":          3,
	"INFOSTATS":    4,
	"INFOCAPACITY": 5,
	"INFOREPL":     6,
	"MGET":         7,
	"INFOSERVER":   8,
}

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}
func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}
func (x *Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Type_value, data, "Type")
	if err != nil {
		return err
	}
	*x = Type(value)
	return nil
}
func (Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SyncType int32

const (
	SyncType_CMD  SyncType = 0
	SyncType_SKIP SyncType = 1
)

var SyncType_name = map[int32]string{
	0: "CMD",
	1: "SKIP",
}
var SyncType_value = map[string]int32{
	"CMD":  0,
	"SKIP": 1,
}

func (x SyncType) Enum() *SyncType {
	p := new(SyncType)
	*p = x
	return p
}
func (x SyncType) String() string {
	return proto.EnumName(SyncType_name, int32(x))
}
func (x *SyncType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SyncType_value, data, "SyncType")
	if err != nil {
		return err
	}
	*x = SyncType(value)
	return nil
}
func (SyncType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type StatusCode int32

const (
	StatusCode_kOk       StatusCode = 0
	StatusCode_kNotFound StatusCode = 1
	StatusCode_kWait     StatusCode = 2
	StatusCode_kError    StatusCode = 3
	StatusCode_kFallback StatusCode = 4
)

var StatusCode_name = map[int32]string{
	0: "kOk",
	1: "kNotFound",
	2: "kWait",
	3: "kError",
	4: "kFallback",
}
var StatusCode_value = map[string]int32{
	"kOk":       0,
	"kNotFound": 1,
	"kWait":     2,
	"kError":    3,
	"kFallback": 4,
}

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}
func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}
func (x *StatusCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(StatusCode_value, data, "StatusCode")
	if err != nil {
		return err
	}
	*x = StatusCode(value)
	return nil
}
func (StatusCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Node struct {
	Ip               *string `protobuf:"bytes,1,req,name=ip" json:"ip,omitempty"`
	Port             *int32  `protobuf:"varint,2,req,name=port" json:"port,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Node) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *Node) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

type SyncOffset struct {
	Filenum          *int32 `protobuf:"varint,1,req,name=filenum" json:"filenum,omitempty"`
	Offset           *int64 `protobuf:"varint,2,req,name=offset" json:"offset,omitempty"`
	Partition        *int32 `protobuf:"varint,3,opt,name=partition" json:"partition,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SyncOffset) Reset()                    { *m = SyncOffset{} }
func (m *SyncOffset) String() string            { return proto.CompactTextString(m) }
func (*SyncOffset) ProtoMessage()               {}
func (*SyncOffset) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SyncOffset) GetFilenum() int32 {
	if m != nil && m.Filenum != nil {
		return *m.Filenum
	}
	return 0
}

func (m *SyncOffset) GetOffset() int64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *SyncOffset) GetPartition() int32 {
	if m != nil && m.Partition != nil {
		return *m.Partition
	}
	return 0
}

type KeyExpire struct {
	Base             *int32 `protobuf:"varint,1,opt,name=base" json:"base,omitempty"`
	Ttl              *int32 `protobuf:"varint,2,req,name=ttl" json:"ttl,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *KeyExpire) Reset()                    { *m = KeyExpire{} }
func (m *KeyExpire) String() string            { return proto.CompactTextString(m) }
func (*KeyExpire) ProtoMessage()               {}
func (*KeyExpire) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *KeyExpire) GetBase() int32 {
	if m != nil && m.Base != nil {
		return *m.Base
	}
	return 0
}

func (m *KeyExpire) GetTtl() int32 {
	if m != nil && m.Ttl != nil {
		return *m.Ttl
	}
	return 0
}

type PartitionState struct {
	PartitionId      *int32      `protobuf:"varint,1,req,name=partition_id,json=partitionId" json:"partition_id,omitempty"`
	Role             *string     `protobuf:"bytes,2,req,name=role" json:"role,omitempty"`
	ReplState        *string     `protobuf:"bytes,3,req,name=repl_state,json=replState" json:"repl_state,omitempty"`
	Master           *Node       `protobuf:"bytes,4,req,name=master" json:"master,omitempty"`
	Slaves           []*Node     `protobuf:"bytes,5,rep,name=slaves" json:"slaves,omitempty"`
	SyncOffset       *SyncOffset `protobuf:"bytes,6,req,name=sync_offset,json=syncOffset" json:"sync_offset,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *PartitionState) Reset()                    { *m = PartitionState{} }
func (m *PartitionState) String() string            { return proto.CompactTextString(m) }
func (*PartitionState) ProtoMessage()               {}
func (*PartitionState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PartitionState) GetPartitionId() int32 {
	if m != nil && m.PartitionId != nil {
		return *m.PartitionId
	}
	return 0
}

func (m *PartitionState) GetRole() string {
	if m != nil && m.Role != nil {
		return *m.Role
	}
	return ""
}

func (m *PartitionState) GetReplState() string {
	if m != nil && m.ReplState != nil {
		return *m.ReplState
	}
	return ""
}

func (m *PartitionState) GetMaster() *Node {
	if m != nil {
		return m.Master
	}
	return nil
}

func (m *PartitionState) GetSlaves() []*Node {
	if m != nil {
		return m.Slaves
	}
	return nil
}

func (m *PartitionState) GetSyncOffset() *SyncOffset {
	if m != nil {
		return m.SyncOffset
	}
	return nil
}

type CmdRequest struct {
	Type             *Type            `protobuf:"varint,1,req,name=type,enum=client.Type" json:"type,omitempty"`
	Sync             *CmdRequest_Sync `protobuf:"bytes,2,opt,name=sync" json:"sync,omitempty"`
	Set              *CmdRequest_Set  `protobuf:"bytes,3,opt,name=set" json:"set,omitempty"`
	Get              *CmdRequest_Get  `protobuf:"bytes,4,opt,name=get" json:"get,omitempty"`
	Del              *CmdRequest_Del  `protobuf:"bytes,5,opt,name=del" json:"del,omitempty"`
	Info             *CmdRequest_Info `protobuf:"bytes,6,opt,name=info" json:"info,omitempty"`
	Mget             *CmdRequest_Mget `protobuf:"bytes,7,opt,name=mget" json:"mget,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *CmdRequest) Reset()                    { *m = CmdRequest{} }
func (m *CmdRequest) String() string            { return proto.CompactTextString(m) }
func (*CmdRequest) ProtoMessage()               {}
func (*CmdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CmdRequest) GetType() Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Type_SYNC
}

func (m *CmdRequest) GetSync() *CmdRequest_Sync {
	if m != nil {
		return m.Sync
	}
	return nil
}

func (m *CmdRequest) GetSet() *CmdRequest_Set {
	if m != nil {
		return m.Set
	}
	return nil
}

func (m *CmdRequest) GetGet() *CmdRequest_Get {
	if m != nil {
		return m.Get
	}
	return nil
}

func (m *CmdRequest) GetDel() *CmdRequest_Del {
	if m != nil {
		return m.Del
	}
	return nil
}

func (m *CmdRequest) GetInfo() *CmdRequest_Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *CmdRequest) GetMget() *CmdRequest_Mget {
	if m != nil {
		return m.Mget
	}
	return nil
}

// Sync
type CmdRequest_Sync struct {
	Node             *Node       `protobuf:"bytes,1,req,name=node" json:"node,omitempty"`
	TableName        *string     `protobuf:"bytes,2,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	SyncOffset       *SyncOffset `protobuf:"bytes,3,req,name=sync_offset,json=syncOffset" json:"sync_offset,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *CmdRequest_Sync) Reset()                    { *m = CmdRequest_Sync{} }
func (m *CmdRequest_Sync) String() string            { return proto.CompactTextString(m) }
func (*CmdRequest_Sync) ProtoMessage()               {}
func (*CmdRequest_Sync) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

func (m *CmdRequest_Sync) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *CmdRequest_Sync) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *CmdRequest_Sync) GetSyncOffset() *SyncOffset {
	if m != nil {
		return m.SyncOffset
	}
	return nil
}

type CmdRequest_Set struct {
	TableName        *string    `protobuf:"bytes,1,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	Key              *string    `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
	Value            []byte     `protobuf:"bytes,3,req,name=value" json:"value,omitempty"`
	Uuid             *string    `protobuf:"bytes,4,opt,name=uuid" json:"uuid,omitempty"`
	Expire           *KeyExpire `protobuf:"bytes,5,opt,name=expire" json:"expire,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *CmdRequest_Set) Reset()                    { *m = CmdRequest_Set{} }
func (m *CmdRequest_Set) String() string            { return proto.CompactTextString(m) }
func (*CmdRequest_Set) ProtoMessage()               {}
func (*CmdRequest_Set) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 1} }

func (m *CmdRequest_Set) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *CmdRequest_Set) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *CmdRequest_Set) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *CmdRequest_Set) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

func (m *CmdRequest_Set) GetExpire() *KeyExpire {
	if m != nil {
		return m.Expire
	}
	return nil
}

type CmdRequest_Get struct {
	TableName        *string `protobuf:"bytes,1,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	Key              *string `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
	Uuid             *string `protobuf:"bytes,3,opt,name=uuid" json:"uuid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CmdRequest_Get) Reset()                    { *m = CmdRequest_Get{} }
func (m *CmdRequest_Get) String() string            { return proto.CompactTextString(m) }
func (*CmdRequest_Get) ProtoMessage()               {}
func (*CmdRequest_Get) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 2} }

func (m *CmdRequest_Get) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *CmdRequest_Get) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *CmdRequest_Get) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

// Delete
type CmdRequest_Del struct {
	TableName        *string `protobuf:"bytes,1,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	Key              *string `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
	Uuid             *string `protobuf:"bytes,3,opt,name=uuid" json:"uuid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CmdRequest_Del) Reset()                    { *m = CmdRequest_Del{} }
func (m *CmdRequest_Del) String() string            { return proto.CompactTextString(m) }
func (*CmdRequest_Del) ProtoMessage()               {}
func (*CmdRequest_Del) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 3} }

func (m *CmdRequest_Del) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *CmdRequest_Del) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *CmdRequest_Del) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

type CmdRequest_Info struct {
	TableName        *string `protobuf:"bytes,1,opt,name=table_name,json=tableName" json:"table_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CmdRequest_Info) Reset()                    { *m = CmdRequest_Info{} }
func (m *CmdRequest_Info) String() string            { return proto.CompactTextString(m) }
func (*CmdRequest_Info) ProtoMessage()               {}
func (*CmdRequest_Info) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 4} }

func (m *CmdRequest_Info) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

type CmdRequest_Mget struct {
	TableName        *string  `protobuf:"bytes,1,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	Keys             []string `protobuf:"bytes,2,rep,name=keys" json:"keys,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CmdRequest_Mget) Reset()                    { *m = CmdRequest_Mget{} }
func (m *CmdRequest_Mget) String() string            { return proto.CompactTextString(m) }
func (*CmdRequest_Mget) ProtoMessage()               {}
func (*CmdRequest_Mget) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 5} }

func (m *CmdRequest_Mget) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *CmdRequest_Mget) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type CmdResponse struct {
	Type             *Type                       `protobuf:"varint,1,req,name=type,enum=client.Type" json:"type,omitempty"`
	Code             *StatusCode                 `protobuf:"varint,2,req,name=code,enum=client.StatusCode" json:"code,omitempty"`
	Msg              *string                     `protobuf:"bytes,3,opt,name=msg" json:"msg,omitempty"`
	Sync             *CmdResponse_Sync           `protobuf:"bytes,4,opt,name=sync" json:"sync,omitempty"`
	Get              *CmdResponse_Get            `protobuf:"bytes,5,opt,name=get" json:"get,omitempty"`
	Redirect         *Node                       `protobuf:"bytes,6,opt,name=redirect" json:"redirect,omitempty"`
	InfoStats        []*CmdResponse_InfoStats    `protobuf:"bytes,7,rep,name=info_stats,json=infoStats" json:"info_stats,omitempty"`
	InfoCapacity     []*CmdResponse_InfoCapacity `protobuf:"bytes,8,rep,name=info_capacity,json=infoCapacity" json:"info_capacity,omitempty"`
	InfoRepl         []*CmdResponse_InfoRepl     `protobuf:"bytes,9,rep,name=info_repl,json=infoRepl" json:"info_repl,omitempty"`
	Mget             []*CmdResponse_Mget         `protobuf:"bytes,10,rep,name=mget" json:"mget,omitempty"`
	InfoServer       *CmdResponse_InfoServer     `protobuf:"bytes,11,opt,name=info_server,json=infoServer" json:"info_server,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *CmdResponse) Reset()                    { *m = CmdResponse{} }
func (m *CmdResponse) String() string            { return proto.CompactTextString(m) }
func (*CmdResponse) ProtoMessage()               {}
func (*CmdResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CmdResponse) GetType() Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Type_SYNC
}

func (m *CmdResponse) GetCode() StatusCode {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return StatusCode_kOk
}

func (m *CmdResponse) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func (m *CmdResponse) GetSync() *CmdResponse_Sync {
	if m != nil {
		return m.Sync
	}
	return nil
}

func (m *CmdResponse) GetGet() *CmdResponse_Get {
	if m != nil {
		return m.Get
	}
	return nil
}

func (m *CmdResponse) GetRedirect() *Node {
	if m != nil {
		return m.Redirect
	}
	return nil
}

func (m *CmdResponse) GetInfoStats() []*CmdResponse_InfoStats {
	if m != nil {
		return m.InfoStats
	}
	return nil
}

func (m *CmdResponse) GetInfoCapacity() []*CmdResponse_InfoCapacity {
	if m != nil {
		return m.InfoCapacity
	}
	return nil
}

func (m *CmdResponse) GetInfoRepl() []*CmdResponse_InfoRepl {
	if m != nil {
		return m.InfoRepl
	}
	return nil
}

func (m *CmdResponse) GetMget() []*CmdResponse_Mget {
	if m != nil {
		return m.Mget
	}
	return nil
}

func (m *CmdResponse) GetInfoServer() *CmdResponse_InfoServer {
	if m != nil {
		return m.InfoServer
	}
	return nil
}

type CmdResponse_Sync struct {
	TableName        *string     `protobuf:"bytes,1,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	SyncOffset       *SyncOffset `protobuf:"bytes,2,req,name=sync_offset,json=syncOffset" json:"sync_offset,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *CmdResponse_Sync) Reset()                    { *m = CmdResponse_Sync{} }
func (m *CmdResponse_Sync) String() string            { return proto.CompactTextString(m) }
func (*CmdResponse_Sync) ProtoMessage()               {}
func (*CmdResponse_Sync) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

func (m *CmdResponse_Sync) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *CmdResponse_Sync) GetSyncOffset() *SyncOffset {
	if m != nil {
		return m.SyncOffset
	}
	return nil
}

type CmdResponse_Get struct {
	Value            []byte `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CmdResponse_Get) Reset()                    { *m = CmdResponse_Get{} }
func (m *CmdResponse_Get) String() string            { return proto.CompactTextString(m) }
func (*CmdResponse_Get) ProtoMessage()               {}
func (*CmdResponse_Get) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 1} }

func (m *CmdResponse_Get) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// InfoStats
type CmdResponse_InfoStats struct {
	TableName        *string `protobuf:"bytes,1,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	TotalQuerys      *int64  `protobuf:"varint,2,req,name=total_querys,json=totalQuerys" json:"total_querys,omitempty"`
	Qps              *int32  `protobuf:"varint,3,req,name=qps" json:"qps,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CmdResponse_InfoStats) Reset()                    { *m = CmdResponse_InfoStats{} }
func (m *CmdResponse_InfoStats) String() string            { return proto.CompactTextString(m) }
func (*CmdResponse_InfoStats) ProtoMessage()               {}
func (*CmdResponse_InfoStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 2} }

func (m *CmdResponse_InfoStats) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *CmdResponse_InfoStats) GetTotalQuerys() int64 {
	if m != nil && m.TotalQuerys != nil {
		return *m.TotalQuerys
	}
	return 0
}

func (m *CmdResponse_InfoStats) GetQps() int32 {
	if m != nil && m.Qps != nil {
		return *m.Qps
	}
	return 0
}

// InfoCapacity
type CmdResponse_InfoCapacity struct {
	TableName        *string `protobuf:"bytes,1,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	Used             *int64  `protobuf:"varint,2,req,name=used" json:"used,omitempty"`
	Remain           *int64  `protobuf:"varint,3,req,name=remain" json:"remain,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CmdResponse_InfoCapacity) Reset()                    { *m = CmdResponse_InfoCapacity{} }
func (m *CmdResponse_InfoCapacity) String() string            { return proto.CompactTextString(m) }
func (*CmdResponse_InfoCapacity) ProtoMessage()               {}
func (*CmdResponse_InfoCapacity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 3} }

func (m *CmdResponse_InfoCapacity) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *CmdResponse_InfoCapacity) GetUsed() int64 {
	if m != nil && m.Used != nil {
		return *m.Used
	}
	return 0
}

func (m *CmdResponse_InfoCapacity) GetRemain() int64 {
	if m != nil && m.Remain != nil {
		return *m.Remain
	}
	return 0
}

// InfoRepl
type CmdResponse_InfoRepl struct {
	TableName        *string           `protobuf:"bytes,1,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	PartitionCnt     *int64            `protobuf:"varint,2,req,name=partition_cnt,json=partitionCnt" json:"partition_cnt,omitempty"`
	PartitionState   []*PartitionState `protobuf:"bytes,3,rep,name=partition_state,json=partitionState" json:"partition_state,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *CmdResponse_InfoRepl) Reset()                    { *m = CmdResponse_InfoRepl{} }
func (m *CmdResponse_InfoRepl) String() string            { return proto.CompactTextString(m) }
func (*CmdResponse_InfoRepl) ProtoMessage()               {}
func (*CmdResponse_InfoRepl) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 4} }

func (m *CmdResponse_InfoRepl) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *CmdResponse_InfoRepl) GetPartitionCnt() int64 {
	if m != nil && m.PartitionCnt != nil {
		return *m.PartitionCnt
	}
	return 0
}

func (m *CmdResponse_InfoRepl) GetPartitionState() []*PartitionState {
	if m != nil {
		return m.PartitionState
	}
	return nil
}

// Mget
type CmdResponse_Mget struct {
	Key              *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            []byte  `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CmdResponse_Mget) Reset()                    { *m = CmdResponse_Mget{} }
func (m *CmdResponse_Mget) String() string            { return proto.CompactTextString(m) }
func (*CmdResponse_Mget) ProtoMessage()               {}
func (*CmdResponse_Mget) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 5} }

func (m *CmdResponse_Mget) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *CmdResponse_Mget) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// InfoServer
type CmdResponse_InfoServer struct {
	Epoch            *int64   `protobuf:"varint,1,req,name=epoch" json:"epoch,omitempty"`
	TableNames       []string `protobuf:"bytes,2,rep,name=table_names,json=tableNames" json:"table_names,omitempty"`
	CurMeta          *Node    `protobuf:"bytes,3,req,name=cur_meta,json=curMeta" json:"cur_meta,omitempty"`
	MetaRenewing     *bool    `protobuf:"varint,4,req,name=meta_renewing,json=metaRenewing" json:"meta_renewing,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CmdResponse_InfoServer) Reset()                    { *m = CmdResponse_InfoServer{} }
func (m *CmdResponse_InfoServer) String() string            { return proto.CompactTextString(m) }
func (*CmdResponse_InfoServer) ProtoMessage()               {}
func (*CmdResponse_InfoServer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 6} }

func (m *CmdResponse_InfoServer) GetEpoch() int64 {
	if m != nil && m.Epoch != nil {
		return *m.Epoch
	}
	return 0
}

func (m *CmdResponse_InfoServer) GetTableNames() []string {
	if m != nil {
		return m.TableNames
	}
	return nil
}

func (m *CmdResponse_InfoServer) GetCurMeta() *Node {
	if m != nil {
		return m.CurMeta
	}
	return nil
}

func (m *CmdResponse_InfoServer) GetMetaRenewing() bool {
	if m != nil && m.MetaRenewing != nil {
		return *m.MetaRenewing
	}
	return false
}

type BinlogSkip struct {
	TableName        *string `protobuf:"bytes,1,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	PartitionId      *int32  `protobuf:"varint,2,req,name=partition_id,json=partitionId" json:"partition_id,omitempty"`
	Gap              *int64  `protobuf:"varint,3,req,name=gap" json:"gap,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BinlogSkip) Reset()                    { *m = BinlogSkip{} }
func (m *BinlogSkip) String() string            { return proto.CompactTextString(m) }
func (*BinlogSkip) ProtoMessage()               {}
func (*BinlogSkip) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *BinlogSkip) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *BinlogSkip) GetPartitionId() int32 {
	if m != nil && m.PartitionId != nil {
		return *m.PartitionId
	}
	return 0
}

func (m *BinlogSkip) GetGap() int64 {
	if m != nil && m.Gap != nil {
		return *m.Gap
	}
	return 0
}

type SyncRequest struct {
	SyncType         *SyncType   `protobuf:"varint,1,req,name=sync_type,json=syncType,enum=client.SyncType" json:"sync_type,omitempty"`
	Epoch            *int64      `protobuf:"varint,2,req,name=epoch" json:"epoch,omitempty"`
	From             *Node       `protobuf:"bytes,3,req,name=from" json:"from,omitempty"`
	SyncOffset       *SyncOffset `protobuf:"bytes,4,req,name=sync_offset,json=syncOffset" json:"sync_offset,omitempty"`
	Request          *CmdRequest `protobuf:"bytes,5,opt,name=request" json:"request,omitempty"`
	BinlogSkip       *BinlogSkip `protobuf:"bytes,6,opt,name=binlog_skip,json=binlogSkip" json:"binlog_skip,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *SyncRequest) Reset()                    { *m = SyncRequest{} }
func (m *SyncRequest) String() string            { return proto.CompactTextString(m) }
func (*SyncRequest) ProtoMessage()               {}
func (*SyncRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SyncRequest) GetSyncType() SyncType {
	if m != nil && m.SyncType != nil {
		return *m.SyncType
	}
	return SyncType_CMD
}

func (m *SyncRequest) GetEpoch() int64 {
	if m != nil && m.Epoch != nil {
		return *m.Epoch
	}
	return 0
}

func (m *SyncRequest) GetFrom() *Node {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *SyncRequest) GetSyncOffset() *SyncOffset {
	if m != nil {
		return m.SyncOffset
	}
	return nil
}

func (m *SyncRequest) GetRequest() *CmdRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *SyncRequest) GetBinlogSkip() *BinlogSkip {
	if m != nil {
		return m.BinlogSkip
	}
	return nil
}

func init() {
	proto.RegisterType((*Node)(nil), "client.Node")
	proto.RegisterType((*SyncOffset)(nil), "client.SyncOffset")
	proto.RegisterType((*KeyExpire)(nil), "client.KeyExpire")
	proto.RegisterType((*PartitionState)(nil), "client.PartitionState")
	proto.RegisterType((*CmdRequest)(nil), "client.CmdRequest")
	proto.RegisterType((*CmdRequest_Sync)(nil), "client.CmdRequest.Sync")
	proto.RegisterType((*CmdRequest_Set)(nil), "client.CmdRequest.Set")
	proto.RegisterType((*CmdRequest_Get)(nil), "client.CmdRequest.Get")
	proto.RegisterType((*CmdRequest_Del)(nil), "client.CmdRequest.Del")
	proto.RegisterType((*CmdRequest_Info)(nil), "client.CmdRequest.Info")
	proto.RegisterType((*CmdRequest_Mget)(nil), "client.CmdRequest.Mget")
	proto.RegisterType((*CmdResponse)(nil), "client.CmdResponse")
	proto.RegisterType((*CmdResponse_Sync)(nil), "client.CmdResponse.Sync")
	proto.RegisterType((*CmdResponse_Get)(nil), "client.CmdResponse.Get")
	proto.RegisterType((*CmdResponse_InfoStats)(nil), "client.CmdResponse.InfoStats")
	proto.RegisterType((*CmdResponse_InfoCapacity)(nil), "client.CmdResponse.InfoCapacity")
	proto.RegisterType((*CmdResponse_InfoRepl)(nil), "client.CmdResponse.InfoRepl")
	proto.RegisterType((*CmdResponse_Mget)(nil), "client.CmdResponse.Mget")
	proto.RegisterType((*CmdResponse_InfoServer)(nil), "client.CmdResponse.InfoServer")
	proto.RegisterType((*BinlogSkip)(nil), "client.BinlogSkip")
	proto.RegisterType((*SyncRequest)(nil), "client.SyncRequest")
	proto.RegisterEnum("client.Type", Type_name, Type_value)
	proto.RegisterEnum("client.SyncType", SyncType_name, SyncType_value)
	proto.RegisterEnum("client.StatusCode", StatusCode_name, StatusCode_value)
}

func init() { proto.RegisterFile("client.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x56, 0xeb, 0x6e, 0xe3, 0xc4,
	0x17, 0x5f, 0x5f, 0x72, 0xf1, 0x49, 0xb6, 0x7f, 0xff, 0x47, 0x68, 0xb1, 0xc2, 0x2e, 0x64, 0xc3,
	0x2d, 0x5b, 0x96, 0x4a, 0x2c, 0x9f, 0x56, 0x42, 0x42, 0x25, 0x4d, 0xab, 0xee, 0x6e, 0x2f, 0x4c,
	0x22, 0x50, 0x11, 0x52, 0x70, 0x9d, 0x49, 0xb0, 0xe2, 0xd8, 0xae, 0x3d, 0x29, 0x44, 0xe2, 0x0d,
	0x40, 0x42, 0xbc, 0x04, 0xef, 0xc0, 0x13, 0xf1, 0x1a, 0xe8, 0x1c, 0x8f, 0xe3, 0x24, 0x4d, 0xd4,
	0x08, 0xf1, 0xed, 0xcc, 0xcc, 0x6f, 0x7e, 0xe7, 0xcc, 0xb9, 0x0e, 0xd4, 0xbd, 0xc0, 0x17, 0xa1,
	0x3c, 0x88, 0x93, 0x48, 0x46, 0xac, 0x9c, 0xad, 0x5a, 0xfb, 0x60, 0x9e, 0x47, 0x43, 0xc1, 0xf6,
	0x40, 0xf7, 0x63, 0x47, 0x6b, 0xea, 0x6d, 0x8b, 0xeb, 0x7e, 0xcc, 0x18, 0x98, 0x71, 0x94, 0x48,
	0x47, 0x6f, 0xea, 0xed, 0x12, 0x27, 0xb9, 0xf5, 0x3d, 0x40, 0x6f, 0x1e, 0x7a, 0x17, 0xa3, 0x51,
	0x2a, 0x24, 0x73, 0xa0, 0x32, 0xf2, 0x03, 0x11, 0xce, 0xa6, 0x74, 0xad, 0xc4, 0xf3, 0x25, 0x7b,
	0x04, 0xe5, 0x88, 0x30, 0x74, 0xdb, 0xe0, 0x6a, 0xc5, 0x1e, 0x83, 0x15, 0xbb, 0x89, 0xf4, 0xa5,
	0x1f, 0x85, 0x8e, 0xd1, 0xd4, 0xda, 0x25, 0x5e, 0x6c, 0xb4, 0x3e, 0x03, 0xeb, 0xb5, 0x98, 0x77,
	0x7f, 0x8e, 0xfd, 0x44, 0xa0, 0xfa, 0x6b, 0x37, 0x15, 0x8e, 0x46, 0x28, 0x92, 0x99, 0x0d, 0x86,
	0x94, 0x81, 0xb2, 0x08, 0xc5, 0xd6, 0xdf, 0x1a, 0xec, 0x5d, 0xe6, 0x04, 0x3d, 0xe9, 0x4a, 0xc1,
	0x9e, 0x42, 0x7d, 0x41, 0x39, 0xf0, 0x87, 0xca, 0xb4, 0xda, 0x62, 0xef, 0x74, 0x88, 0xdc, 0x49,
	0x14, 0x08, 0x22, 0xb2, 0x38, 0xc9, 0xec, 0x09, 0x40, 0x22, 0xe2, 0x60, 0x90, 0x22, 0x89, 0x63,
	0xd0, 0x89, 0x85, 0x3b, 0x19, 0xeb, 0x07, 0x50, 0x9e, 0xba, 0xa9, 0x14, 0x89, 0x63, 0x36, 0xf5,
	0x76, 0xed, 0x45, 0xfd, 0x40, 0x39, 0x13, 0x7d, 0xc7, 0xd5, 0x19, 0xa2, 0xd2, 0xc0, 0xbd, 0x15,
	0xa9, 0x53, 0x6a, 0x1a, 0x77, 0x51, 0xd9, 0x19, 0xfb, 0x1c, 0x6a, 0xe9, 0x3c, 0xf4, 0x06, 0xca,
	0x45, 0x65, 0x22, 0x64, 0x39, 0xb4, 0x70, 0x30, 0x87, 0x74, 0x21, 0xb7, 0xfe, 0x2a, 0x03, 0x74,
	0xa6, 0x43, 0x2e, 0x6e, 0x66, 0x22, 0x95, 0xac, 0x09, 0xa6, 0x9c, 0xc7, 0x82, 0x5e, 0xb7, 0x57,
	0xe8, 0xe9, 0xcf, 0x63, 0xc1, 0xe9, 0x84, 0x7d, 0x02, 0x26, 0x5e, 0x77, 0xf4, 0xa6, 0xd6, 0xae,
	0xbd, 0x78, 0x3b, 0x47, 0x14, 0x1c, 0xa4, 0x89, 0x13, 0x88, 0xb5, 0xc1, 0x40, 0x53, 0x0c, 0xc2,
	0x3e, 0xda, 0x84, 0x15, 0x92, 0x23, 0x04, 0x91, 0x63, 0x21, 0x1d, 0x73, 0x2b, 0xf2, 0x04, 0x91,
	0xe3, 0x0c, 0x39, 0x14, 0x81, 0x53, 0xda, 0x8a, 0x3c, 0x12, 0x01, 0x47, 0x08, 0x9a, 0xea, 0x87,
	0xa3, 0xc8, 0x29, 0x6f, 0x35, 0xf5, 0x34, 0x1c, 0x45, 0x9c, 0x40, 0x08, 0x9e, 0xa2, 0x05, 0x95,
	0xad, 0xe0, 0xb3, 0xb1, 0x90, 0x9c, 0x40, 0x8d, 0x5f, 0xc0, 0xc4, 0x57, 0xa2, 0xbb, 0xc2, 0x68,
	0x98, 0xb9, 0x6b, 0x3d, 0x2c, 0x74, 0x82, 0xf1, 0x97, 0xee, 0x75, 0x20, 0x06, 0xa1, 0x3b, 0xcd,
	0x33, 0xc3, 0xa2, 0x9d, 0x73, 0x77, 0x2a, 0xd6, 0x63, 0x66, 0xec, 0x12, 0xb3, 0xc6, 0xaf, 0x1a,
	0x18, 0x3d, 0x21, 0xd7, 0xb8, 0xb5, 0x75, 0x6e, 0x1b, 0x8c, 0x89, 0x98, 0x2b, 0x9d, 0x28, 0xb2,
	0xb7, 0xa0, 0x74, 0xeb, 0x06, 0xb3, 0x2c, 0x0f, 0xeb, 0x3c, 0x5b, 0x60, 0xda, 0xce, 0x66, 0xfe,
	0x90, 0x7c, 0x6f, 0x71, 0x92, 0xd9, 0x33, 0x28, 0x0b, 0x2a, 0x18, 0xe5, 0xe7, 0xff, 0xe7, 0x26,
	0x2d, 0x2a, 0x89, 0x2b, 0x40, 0xe3, 0x15, 0x18, 0x27, 0xff, 0xc6, 0x98, 0x5c, 0xad, 0x51, 0xa8,
	0x45, 0xae, 0x23, 0x11, 0xfc, 0x37, 0x5c, 0x1f, 0x82, 0x89, 0xe1, 0xbd, 0x43, 0xa6, 0xad, 0x90,
	0x35, 0x5e, 0x82, 0x89, 0x81, 0xbd, 0x4f, 0x27, 0x03, 0x73, 0x22, 0xe6, 0xa9, 0xa3, 0x37, 0x0d,
	0xd4, 0x80, 0x72, 0xeb, 0x4f, 0x0b, 0x6a, 0x94, 0x1f, 0x69, 0x1c, 0x85, 0xa9, 0xd8, 0xa1, 0x78,
	0x3e, 0x02, 0xd3, 0xc3, 0x7c, 0xd1, 0x09, 0x51, 0xc4, 0x59, 0xba, 0x72, 0x96, 0x76, 0x28, 0x6b,
	0xf0, 0x1c, 0x5f, 0x38, 0x4d, 0xc7, 0xea, 0x39, 0x28, 0xb2, 0xe7, 0xaa, 0xec, 0xb2, 0x02, 0x71,
	0x56, 0xd2, 0x33, 0x53, 0xbf, 0x5c, 0x77, 0xcf, 0xb2, 0x6a, 0x2a, 0x6d, 0xc8, 0x65, 0x05, 0x5e,
	0x2a, 0xa7, 0x6a, 0x22, 0x86, 0x7e, 0x22, 0x3c, 0xa9, 0x0a, 0x65, 0x35, 0x8d, 0x17, 0xa7, 0xec,
	0x0b, 0x00, 0xac, 0x14, 0x6a, 0x65, 0xa9, 0x53, 0xa1, 0x4e, 0xf4, 0x64, 0x13, 0x37, 0xba, 0x1d,
	0x9f, 0x94, 0x72, 0xcb, 0xcf, 0x45, 0xd6, 0x85, 0x87, 0x74, 0xdb, 0x73, 0x63, 0xd7, 0xf3, 0xe5,
	0xdc, 0xa9, 0x12, 0x41, 0x73, 0x1b, 0x41, 0x47, 0xe1, 0x78, 0xdd, 0x5f, 0x5a, 0xb1, 0x97, 0x40,
	0x9c, 0x03, 0x6c, 0xa1, 0x8e, 0x45, 0x14, 0x8f, 0xb7, 0x51, 0x70, 0x11, 0x07, 0xbc, 0xea, 0x2b,
	0x09, 0x5d, 0x48, 0x15, 0x0e, 0x74, 0x6b, 0xa3, 0x0b, 0x8b, 0x12, 0x67, 0x5f, 0x42, 0x2d, 0x7b,
	0xad, 0x48, 0x6e, 0x45, 0xe2, 0xd4, 0xc8, 0x35, 0xef, 0x6e, 0x7d, 0x2e, 0xa1, 0x38, 0x39, 0x28,
	0x93, 0x1b, 0xdf, 0xa9, 0x1e, 0x71, 0x4f, 0x62, 0xad, 0x75, 0x00, 0x7d, 0xa7, 0x0e, 0xf0, 0x4e,
	0x56, 0x73, 0x8b, 0x7a, 0xc6, 0xac, 0xce, 0xeb, 0xb9, 0x31, 0x00, 0x6b, 0x11, 0x81, 0xfb, 0xb4,
	0x3f, 0x85, 0xba, 0x8c, 0xa4, 0x1b, 0x0c, 0x6e, 0x66, 0x22, 0xa1, 0xf4, 0xc6, 0xb9, 0x5a, 0xa3,
	0xbd, 0xaf, 0x69, 0x0b, 0x73, 0xf1, 0x26, 0x4e, 0xa9, 0x65, 0x94, 0x38, 0x8a, 0x8d, 0x2b, 0xa8,
	0x2f, 0x47, 0x68, 0x87, 0xd2, 0x99, 0xa5, 0x62, 0xa8, 0xb8, 0x49, 0xc6, 0x49, 0x9e, 0x88, 0xa9,
	0xeb, 0x87, 0xc4, 0x6b, 0x70, 0xb5, 0x6a, 0xfc, 0xae, 0x41, 0x35, 0x0f, 0xdd, 0x7d, 0xbc, 0xef,
	0xc3, 0xc3, 0x62, 0x22, 0x7b, 0x61, 0xfe, 0x29, 0x28, 0xc6, 0x74, 0x27, 0xc4, 0x30, 0xfe, 0xaf,
	0x00, 0xe5, 0x43, 0xd8, 0x58, 0x9e, 0x1c, 0xab, 0x73, 0x9e, 0xef, 0xc5, 0x2b, 0xeb, 0xc6, 0x81,
	0xea, 0x0f, 0xaa, 0xe9, 0x68, 0x1b, 0xba, 0xa9, 0xbe, 0xd4, 0x4d, 0x1b, 0x7f, 0x68, 0x00, 0x45,
	0x46, 0x20, 0x48, 0xc4, 0x91, 0xf7, 0x23, 0x5d, 0x34, 0x78, 0xb6, 0x60, 0xef, 0x41, 0xad, 0x78,
	0x59, 0xde, 0x54, 0x60, 0xf1, 0xb4, 0x94, 0x7d, 0x0c, 0x55, 0x6f, 0x96, 0x0c, 0xa6, 0x42, 0xba,
	0x6a, 0x28, 0xac, 0x56, 0x65, 0xc5, 0x9b, 0x25, 0x67, 0x42, 0xba, 0xe8, 0x04, 0x04, 0x0d, 0x12,
	0x11, 0x8a, 0x9f, 0xfc, 0x70, 0x4c, 0xff, 0x88, 0x2a, 0xaf, 0xe3, 0x26, 0x57, 0x7b, 0xad, 0x1f,
	0x00, 0xbe, 0xf2, 0xc3, 0x20, 0x1a, 0xf7, 0x26, 0x7e, 0xbc, 0x43, 0x4a, 0xac, 0x7c, 0x74, 0xf4,
	0xbb, 0x1f, 0x1d, 0x1b, 0x8c, 0xb1, 0x1b, 0xab, 0xd0, 0xa1, 0xd8, 0xfa, 0x4d, 0x87, 0x1a, 0xf5,
	0x1f, 0xf5, 0x8f, 0xf8, 0x14, 0x2c, 0xca, 0xea, 0xa5, 0x7e, 0x68, 0x2f, 0xe7, 0x34, 0xf5, 0xc4,
	0x6a, 0xaa, 0xa4, 0xc2, 0x4b, 0xfa, 0xb2, 0x97, 0x9a, 0x60, 0x8e, 0x92, 0x68, 0xba, 0xd1, 0x01,
	0x74, 0xb2, 0x5e, 0x3c, 0xe6, 0x2e, 0xc5, 0xc3, 0x9e, 0x43, 0x25, 0xc9, 0xcc, 0x54, 0x0d, 0x92,
	0xdd, 0x1d, 0xf6, 0x3c, 0x87, 0xa0, 0x8a, 0x6b, 0xf2, 0xdd, 0x20, 0x9d, 0xf8, 0xb1, 0x6a, 0x91,
	0x8b, 0x1b, 0x85, 0x5b, 0x39, 0x5c, 0x2f, 0xe4, 0x7d, 0x09, 0x26, 0xbd, 0xab, 0x0a, 0x66, 0xef,
	0xea, 0xbc, 0x63, 0x3f, 0x60, 0x15, 0x30, 0x7a, 0xdd, 0xbe, 0xad, 0xa1, 0x70, 0xd2, 0xed, 0xdb,
	0x3a, 0x0a, 0x47, 0xdd, 0x37, 0xb6, 0xc1, 0x1e, 0x82, 0x75, 0x7a, 0x7e, 0x7c, 0xd1, 0xeb, 0x1f,
	0xf6, 0x7b, 0xb6, 0xc9, 0x6c, 0xa8, 0xe3, 0xb2, 0x73, 0x78, 0x79, 0xd8, 0x39, 0xed, 0x5f, 0xd9,
	0x25, 0x56, 0x87, 0x2a, 0xee, 0xf0, 0xee, 0xe5, 0x1b, 0xbb, 0x8c, 0x9c, 0x67, 0xc8, 0x50, 0x61,
	0x7b, 0x00, 0x74, 0xb1, 0xcb, 0xbf, 0xe9, 0x72, 0xbb, 0xba, 0xff, 0x04, 0xaa, 0xb9, 0x6f, 0x91,
	0xbd, 0x73, 0x76, 0x64, 0x3f, 0x20, 0x13, 0x5e, 0x9f, 0x5e, 0xda, 0xda, 0xfe, 0x2b, 0x80, 0x62,
	0xd0, 0x20, 0x60, 0x72, 0x31, 0xb1, 0x1f, 0xa0, 0xfa, 0xc9, 0x79, 0x24, 0x8f, 0xa3, 0x59, 0x38,
	0xb4, 0x35, 0x66, 0x41, 0x69, 0xf2, 0xad, 0xeb, 0x4b, 0x5b, 0x67, 0x00, 0xe5, 0x49, 0x37, 0x49,
	0xa2, 0x24, 0x33, 0x72, 0x72, 0xec, 0x06, 0xc1, 0xb5, 0xeb, 0x4d, 0x6c, 0xf3, 0x9f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xac, 0x81, 0x7d, 0x54, 0xf4, 0x0b, 0x00, 0x00,
}
